[package]
name = "dstrombe-raytracer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pixels = "0.11.0"
winit = "0.27"
winit_input_helper = "0.13"
rayon = "1.6.1"
fastrand = "1.8.0"
